package models;
// Generated Jan 16, 2019 6:25:18 PM by Hibernate Tools 3.6.0



/**
 * GuardReturnDetail generated by hbm2java
 */
public class GuardReturnDetail  implements java.io.Serializable {


     private Long index;
     private ItemMaster itemMaster;
     private GuardReturnMaster guardReturnMaster;
     private int qty;
     private String remark;

    public GuardReturnDetail() {
    }

	
    public GuardReturnDetail(int qty, String remark) {
        this.qty = qty;
        this.remark = remark;
    }
    public GuardReturnDetail(ItemMaster itemMaster, GuardReturnMaster guardReturnMaster, int qty, String remark) {
       this.itemMaster = itemMaster;
       this.guardReturnMaster = guardReturnMaster;
       this.qty = qty;
       this.remark = remark;
    }
   
    public Long getIndex() {
        return this.index;
    }
    
    public void setIndex(Long index) {
        this.index = index;
    }
    public ItemMaster getItemMaster() {
        return this.itemMaster;
    }
    
    public void setItemMaster(ItemMaster itemMaster) {
        this.itemMaster = itemMaster;
    }
    public GuardReturnMaster getGuardReturnMaster() {
        return this.guardReturnMaster;
    }
    
    public void setGuardReturnMaster(GuardReturnMaster guardReturnMaster) {
        this.guardReturnMaster = guardReturnMaster;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


