package models;
// Generated Jan 4, 2019 5:42:06 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * GuardUniformIssue generated by hbm2java
 */
public class GuardUniformIssue  implements java.io.Serializable {


     private Long index;
     private ItemInwards itemInwards;
     private ItemMaster itemMaster;
     private Securityguard securityguard;
     private Date issuedate;
     private int qty;
     private String remark;

    public GuardUniformIssue() {
    }

    public GuardUniformIssue(ItemInwards itemInwards, ItemMaster itemMaster, Securityguard securityguard, Date issuedate, int qty, String remark) {
       this.itemInwards = itemInwards;
       this.itemMaster = itemMaster;
       this.securityguard = securityguard;
       this.issuedate = issuedate;
       this.qty = qty;
       this.remark = remark;
    }
   
    public Long getIndex() {
        return this.index;
    }
    
    public void setIndex(Long index) {
        this.index = index;
    }
    public ItemInwards getItemInwards() {
        return this.itemInwards;
    }
    
    public void setItemInwards(ItemInwards itemInwards) {
        this.itemInwards = itemInwards;
    }
    public ItemMaster getItemMaster() {
        return this.itemMaster;
    }
    
    public void setItemMaster(ItemMaster itemMaster) {
        this.itemMaster = itemMaster;
    }
    public Securityguard getSecurityguard() {
        return this.securityguard;
    }
    
    public void setSecurityguard(Securityguard securityguard) {
        this.securityguard = securityguard;
    }
    public Date getIssuedate() {
        return this.issuedate;
    }
    
    public void setIssuedate(Date issuedate) {
        this.issuedate = issuedate;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


