package models;
// Generated Jan 4, 2019 5:42:06 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * GuardUniformReturn generated by hbm2java
 */
public class GuardUniformReturn  implements java.io.Serializable {


     private Long returnIndex;
     private ItemMaster itemMaster;
     private GuardUniformIssue guarduniformissue;
     private Securityguard securityguard;
     private Date returndate;
     private int qty;
     private String remark;

    public GuardUniformReturn() {
    }

    public GuardUniformReturn(ItemMaster itemMaster, GuardUniformIssue guarduniformissue, Securityguard securityguard, Date returndate, int qty, String remark) {
       this.itemMaster = itemMaster;
       this.guarduniformissue =  guarduniformissue;
       this.securityguard = securityguard;
       this.returndate = returndate;
       this.qty = qty;
       this.remark = remark;
    }
   
    public Long getReturnIndex() {
        return this.returnIndex;
    }
    
    public void setReturnIndex(Long returnIndex) {
        this.returnIndex = returnIndex;
    }
    public ItemMaster getItemMaster() {
        return this.itemMaster;
    }
    
    public void setItemMaster(ItemMaster itemMaster) {
        this.itemMaster = itemMaster;
    }
   
    public Securityguard getSecurityguard() {
        return this.securityguard;
    }
    
    public void setSecurityguard(Securityguard securityguard) {
        this.securityguard = securityguard;
    }
    public Date getReturndate() {
        return this.returndate;
    }
    
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public GuardUniformIssue getGuarduniformissue() {
        return guarduniformissue;
    }

    public void setGuarduniformissue(GuardUniformIssue guarduniformissue) {
        this.guarduniformissue = guarduniformissue;
    }




}


