package models;
// Generated Jan 16, 2019 6:25:18 PM by Hibernate Tools 3.6.0



/**
 * GuardIssueDetail generated by hbm2java
 */
public class GuardIssueDetail  implements java.io.Serializable {


     private Long index;
     private GuardIssueMaster guardIssueMaster;
     private int itemid;
     private String qty;
     private String remark;
     private double sellingPrice;
     private long inwardIndex;

    public GuardIssueDetail() {
    }

	
    public GuardIssueDetail(GuardIssueMaster guardIssueMaster, int itemid, String qty, double sellingPrice, long inwardIndex) {
        this.guardIssueMaster = guardIssueMaster;
        this.itemid = itemid;
        this.qty = qty;
        this.sellingPrice = sellingPrice;
        this.inwardIndex = inwardIndex;
    }
    public GuardIssueDetail(GuardIssueMaster guardIssueMaster, int itemid, String qty, String remark, double sellingPrice, long inwardIndex) {
       this.guardIssueMaster = guardIssueMaster;
       this.itemid = itemid;
       this.qty = qty;
       this.remark = remark;
       this.sellingPrice = sellingPrice;
       this.inwardIndex = inwardIndex;
    }
   
    public Long getIndex() {
        return this.index;
    }
    
    public void setIndex(Long index) {
        this.index = index;
    }
    public GuardIssueMaster getGuardIssueMaster() {
        return this.guardIssueMaster;
    }
    
    public void setGuardIssueMaster(GuardIssueMaster guardIssueMaster) {
        this.guardIssueMaster = guardIssueMaster;
    }
    public int getItemid() {
        return this.itemid;
    }
    
    public void setItemid(int itemid) {
        this.itemid = itemid;
    }
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public long getInwardIndex() {
        return this.inwardIndex;
    }
    
    public void setInwardIndex(long inwardIndex) {
        this.inwardIndex = inwardIndex;
    }




}


