package models;
// Generated Jan 16, 2019 6:25:18 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GuardIssueMaster generated by hbm2java
 */
public class GuardIssueMaster  implements java.io.Serializable {


     private Long issueIndex;
     private Securityguard securityguard;
     private Date issueDate;
     private Set guardIssueDetails = new HashSet(0);
     private Set guardIssueDetails_1 = new HashSet(0);

    public GuardIssueMaster() {
    }

	
    public GuardIssueMaster(Securityguard securityguard, Date issueDate) {
        this.securityguard = securityguard;
        this.issueDate = issueDate;
    }
    public GuardIssueMaster(Securityguard securityguard, Date issueDate, Set guardIssueDetails, Set guardIssueDetails_1) {
       this.securityguard = securityguard;
       this.issueDate = issueDate;
       this.guardIssueDetails = guardIssueDetails;
       this.guardIssueDetails_1 = guardIssueDetails_1;
    }
   
    public Long getIssueIndex() {
        return this.issueIndex;
    }
    
    public void setIssueIndex(Long issueIndex) {
        this.issueIndex = issueIndex;
    }
    public Securityguard getSecurityguard() {
        return this.securityguard;
    }
    
    public void setSecurityguard(Securityguard securityguard) {
        this.securityguard = securityguard;
    }
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }
    public Set getGuardIssueDetails() {
        return this.guardIssueDetails;
    }
    
    public void setGuardIssueDetails(Set guardIssueDetails) {
        this.guardIssueDetails = guardIssueDetails;
    }
    public Set getGuardIssueDetails_1() {
        return this.guardIssueDetails_1;
    }
    
    public void setGuardIssueDetails_1(Set guardIssueDetails_1) {
        this.guardIssueDetails_1 = guardIssueDetails_1;
    }




}


