package models;
// Generated Jan 10, 2019 3:43:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemInwardMaster generated by hbm2java
 */
public class ItemInwardMaster  implements java.io.Serializable {


     private Long inwardIndex;
     private PersonMaster personMaster;
     private Date date;
     private Long billNo;
     private Set itemInwardDetailses = new HashSet(0);

    public ItemInwardMaster() {
    }

	
    public ItemInwardMaster(PersonMaster personMaster, Date date) {
        this.personMaster = personMaster;
        this.date = date;
    }
    public ItemInwardMaster(PersonMaster personMaster, Date date, Long billNo, Set itemInwardDetailses) {
       this.personMaster = personMaster;
       this.date = date;
       this.billNo = billNo;
       this.itemInwardDetailses = itemInwardDetailses;
    }
   
    public Long getInwardIndex() {
        return this.inwardIndex;
    }
    
    public void setInwardIndex(Long inwardIndex) {
        this.inwardIndex = inwardIndex;
    }
    public PersonMaster getPersonMaster() {
        return this.personMaster;
    }
    
    public void setPersonMaster(PersonMaster personMaster) {
        this.personMaster = personMaster;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Long getBillNo() {
        return this.billNo;
    }
    
    public void setBillNo(Long billNo) {
        this.billNo = billNo;
    }
    public Set getItemInwardDetailses() {
        return this.itemInwardDetailses;
    }
    
    public void setItemInwardDetailses(Set itemInwardDetailses) {
        this.itemInwardDetailses = itemInwardDetailses;
    }




}


