package models;
// Generated Jan 4, 2019 5:42:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ItemMaster generated by hbm2java
 */
public class ItemMaster  implements java.io.Serializable {


     private Integer itemid;
     private String itemname;
     private String itemCategory;
     private String subCategory;
     private Set itemInwardses = new HashSet(0);
     private Set personMasters = new HashSet(0);
     private Set guardUniformIssues = new HashSet(0);
     private Set guardUniformReturns = new HashSet(0);
     private Set itemOutwardses = new HashSet(0);
     private String reorder ;
    public ItemMaster() {
    }

	
    public ItemMaster(String itemname, String itemCategory, String subCategory,String reorder) {
        this.itemname = itemname;
        this.itemCategory = itemCategory;
        this.subCategory = subCategory;
        this.reorder=reorder;
    }
    public ItemMaster(String itemname, String itemCategory, String subCategory, Set itemInwardses, Set personMasters, Set guardUniformIssues, Set guardUniformReturns, Set itemOutwardses) {
       this.itemname = itemname;
       this.itemCategory = itemCategory;
       this.subCategory = subCategory;
       this.itemInwardses = itemInwardses;
       this.personMasters = personMasters;
       this.guardUniformIssues = guardUniformIssues;
       this.guardUniformReturns = guardUniformReturns;
       this.itemOutwardses = itemOutwardses;
    }
   
    public Integer getItemid() {
        return this.itemid;
    }
    
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }
    public String getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }
    public String getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }
    public Set getItemInwardses() {
        return this.itemInwardses;
    }
    
    public void setItemInwardses(Set itemInwardses) {
        this.itemInwardses = itemInwardses;
    }
    public Set getPersonMasters() {
        return this.personMasters;
    }
    
    public void setPersonMasters(Set personMasters) {
        this.personMasters = personMasters;
    }
    public Set getGuardUniformIssues() {
        return this.guardUniformIssues;
    }
    
    public void setGuardUniformIssues(Set guardUniformIssues) {
        this.guardUniformIssues = guardUniformIssues;
    }
    public Set getGuardUniformReturns() {
        return this.guardUniformReturns;
    }
    
    public void setGuardUniformReturns(Set guardUniformReturns) {
        this.guardUniformReturns = guardUniformReturns;
    }
    public Set getItemOutwardses() {
        return this.itemOutwardses;
    }
    
    public void setItemOutwardses(Set itemOutwardses) {
        this.itemOutwardses = itemOutwardses;
    }

    public String getReorder() {
        return reorder;
    }

    public void setReorder(String reorder) {
        this.reorder = reorder;
    }




}


