package models;
// Generated Jan 10, 2019 3:43:57 PM by Hibernate Tools 3.6.0



/**
 * ItemOutwardDetails generated by hbm2java
 */
public class ItemOutwardDetails  implements java.io.Serializable {


     private Long outwardDetailIndex;
     private ItemMaster itemMaster;
     private ItemOutwardMaster itemOutwardMaster;
     private int qty;
     private Double sellingPrice;
 private ItemInwardDetails iteminwarddetails;
    public ItemOutwardDetails() {
    }

	
    public ItemOutwardDetails(ItemMaster itemMaster, int qty) {
        this.itemMaster = itemMaster;
        this.qty = qty;
    }
    public ItemOutwardDetails(ItemMaster itemMaster, ItemOutwardMaster itemOutwardMaster, int qty, Double sellingPrice,ItemInwardDetails iteminwarddetails) {
       this.itemMaster = itemMaster;
       this.itemOutwardMaster = itemOutwardMaster;
       this.qty = qty;
       this.sellingPrice = sellingPrice;
       this.iteminwarddetails=iteminwarddetails;
    }
   
    public Long getOutwardDetailIndex() {
        return this.outwardDetailIndex;
    }
    
    public void setOutwardDetailIndex(Long outwardDetailIndex) {
        this.outwardDetailIndex = outwardDetailIndex;
    }
    public ItemMaster getItemMaster() {
        return this.itemMaster;
    }
    
    public void setItemMaster(ItemMaster itemMaster) {
        this.itemMaster = itemMaster;
    }
    public ItemOutwardMaster getItemOutwardMaster() {
        return this.itemOutwardMaster;
    }
    
    public void setItemOutwardMaster(ItemOutwardMaster itemOutwardMaster) {
        this.itemOutwardMaster = itemOutwardMaster;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    public ItemInwardDetails getIteminwarddetails() {
        return iteminwarddetails;
    }

    public void setIteminwarddetails(ItemInwardDetails iteminwarddetails) {
        this.iteminwarddetails = iteminwarddetails;
    }


}


