package models;
// Generated Jan 4, 2019 5:42:06 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemInwards generated by hbm2java
 */
public class ItemInwards  implements java.io.Serializable {


     private Long inwardindex;
     private ItemMaster itemMaster;
     private PersonMaster personMaster;
     private String inwardDate;
     private double qty;
     private long billno;
     private double byingPrice;
     private String remark;
     private Set guardUniformIssues = new HashSet(0);
     private Set guardUniformReturns = new HashSet(0);
     private Set itemOutwardses = new HashSet(0);

    public ItemInwards() {
    }

	
    public ItemInwards(ItemMaster itemMaster, PersonMaster personMaster, String inwardDate, double qty, long billno, double byingPrice) {
        this.itemMaster = itemMaster;
        this.personMaster = personMaster;
        this.inwardDate = inwardDate;
        this.qty = qty;
        this.billno = billno;
        this.byingPrice = byingPrice;
    }
    public ItemInwards(ItemMaster itemMaster, PersonMaster personMaster, String inwardDate, double qty, long billno, double byingPrice, String remark, Set guardUniformIssues, Set guardUniformReturns, Set itemOutwardses) {
       this.itemMaster = itemMaster;
       this.personMaster = personMaster;
       this.inwardDate = inwardDate;
       this.qty = qty;
       this.billno = billno;
       this.byingPrice = byingPrice;
       this.remark = remark;
       this.guardUniformIssues = guardUniformIssues;
       this.guardUniformReturns = guardUniformReturns;
       this.itemOutwardses = itemOutwardses;
    }
   
    public Long getInwardindex() {
        return this.inwardindex;
    }
    
    public void setInwardindex(Long inwardindex) {
        this.inwardindex = inwardindex;
    }
    public ItemMaster getItemMaster() {
        return this.itemMaster;
    }
    
    public void setItemMaster(ItemMaster itemMaster) {
        this.itemMaster = itemMaster;
    }
    public PersonMaster getPersonMaster() {
        return this.personMaster;
    }
    
    public void setPersonMaster(PersonMaster personMaster) {
        this.personMaster = personMaster;
    }
    public String getInwardDate() {
        return this.inwardDate;
    }
    
    public void setInwardDate(String inwardDate) {
        this.inwardDate = inwardDate;
    }
    public double getQty() {
        return this.qty;
    }
    
    public void setQty(double qty) {
        this.qty = qty;
    }
    public long getBillno() {
        return this.billno;
    }
    
    public void setBillno(long billno) {
        this.billno = billno;
    }
    public double getByingPrice() {
        return this.byingPrice;
    }
    
    public void setByingPrice(double byingPrice) {
        this.byingPrice = byingPrice;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getGuardUniformIssues() {
        return this.guardUniformIssues;
    }
    
    public void setGuardUniformIssues(Set guardUniformIssues) {
        this.guardUniformIssues = guardUniformIssues;
    }
    public Set getGuardUniformReturns() {
        return this.guardUniformReturns;
    }
    
    public void setGuardUniformReturns(Set guardUniformReturns) {
        this.guardUniformReturns = guardUniformReturns;
    }
    public Set getItemOutwardses() {
        return this.itemOutwardses;
    }
    
    public void setItemOutwardses(Set itemOutwardses) {
        this.itemOutwardses = itemOutwardses;
    }




}


