package models;
// Generated Jan 10, 2019 3:43:57 PM by Hibernate Tools 3.6.0



/**
 * ItemInwardDetails generated by hbm2java
 */
public class ItemInwardDetails  implements java.io.Serializable {


     private Long inwardDetailIndex;
     private ItemMaster itemMaster;
     private ItemInwardMaster itemInwardMaster;
     private int qty;
     private double purchasePrice;
     private long balance;
     private String remark;

    public ItemInwardDetails() {
    }

    public ItemInwardDetails(ItemMaster itemMaster, ItemInwardMaster itemInwardMaster, int qty, double purchasePrice, long balance, String remark) {
       this.itemMaster = itemMaster;
       this.itemInwardMaster = itemInwardMaster;
       this.qty = qty;
       this.purchasePrice = purchasePrice;
       this.balance = balance;
       this.remark = remark;
    }
   
    public Long getInwardDetailIndex() {
        return this.inwardDetailIndex;
    }
    
    public void setInwardDetailIndex(Long inwardDetailIndex) {
        this.inwardDetailIndex = inwardDetailIndex;
    }
    public ItemMaster getItemMaster() {
        return this.itemMaster;
    }
    
    public void setItemMaster(ItemMaster itemMaster) {
        this.itemMaster = itemMaster;
    }
    public ItemInwardMaster getItemInwardMaster() {
        return this.itemInwardMaster;
    }
    
    public void setItemInwardMaster(ItemInwardMaster itemInwardMaster) {
        this.itemInwardMaster = itemInwardMaster;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public double getPurchasePrice() {
        return this.purchasePrice;
    }
    
    public void setPurchasePrice(double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }
    public long getBalance() {
        return this.balance;
    }
    
    public void setBalance(long balance) {
        this.balance = balance;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


