package models;
// Generated Jan 4, 2019 5:42:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PersonMaster generated by hbm2java
 */
public class PersonMaster  implements java.io.Serializable {


     private Integer pid;
     private String firstname;
     private String midname;
     private String lastname;
     private String persontype;
     private Long contactno;
     private String addline1;
     private String addline2;
     private String city;
     private String state;
     private Integer pincode;
     private String baddress;
     private Set itemInwardses = new HashSet(0);
     private Set itemMasters = new HashSet(0);
     private Set itemOutwardses = new HashSet(0);

    public PersonMaster() {
    }

	
    public PersonMaster(String firstname, String persontype) {
        this.firstname = firstname;
        this.persontype = persontype;
    }
    public PersonMaster(String firstname, String midname, String lastname, String persontype, Long contactno, String addline1, String addline2, String city, String state, Integer pincode, Set itemInwardses, Set itemMasters, Set itemOutwardses) {
       this.firstname = firstname;
       this.midname = midname;
       this.lastname = lastname;
       this.persontype = persontype;
       this.contactno = contactno;
       this.addline1 = addline1;
       this.addline2 = addline2;
       this.city = city;
       this.state = state;
       this.pincode = pincode;
       this.itemInwardses = itemInwardses;
       this.itemMasters = itemMasters;
       this.itemOutwardses = itemOutwardses;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getMidname() {
        return this.midname;
    }
    
    public void setMidname(String midname) {
        this.midname = midname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPersontype() {
        return this.persontype;
    }
    
    public void setPersontype(String persontype) {
        this.persontype = persontype;
    }
    public Long getContactno() {
        return this.contactno;
    }
    
    public void setContactno(Long contactno) {
        this.contactno = contactno;
    }
    public String getAddline1() {
        return this.addline1;
    }
    
    public void setAddline1(String addline1) {
        this.addline1 = addline1;
    }
    public String getAddline2() {
        return this.addline2;
    }
    
    public void setAddline2(String addline2) {
        this.addline2 = addline2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }
    public Set getItemInwardses() {
        return this.itemInwardses;
    }
    
    public void setItemInwardses(Set itemInwardses) {
        this.itemInwardses = itemInwardses;
    }
    public Set getItemMasters() {
        return this.itemMasters;
    }
    
    public void setItemMasters(Set itemMasters) {
        this.itemMasters = itemMasters;
    }
    public Set getItemOutwardses() {
        return this.itemOutwardses;
    }
    
    public void setItemOutwardses(Set itemOutwardses) {
        this.itemOutwardses = itemOutwardses;
    }

    public String getBaddress() {
        return baddress;
    }

    public void setBaddress(String baddress) {
        this.baddress = baddress;
    }




}


