package models;
// Generated Jan 4, 2019 5:42:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Securityguard generated by hbm2java
 */
public class Securityguard  implements java.io.Serializable {


     private Long empcode;
     private String firstname;
     private String midname;
     private String lastname;
     private Long contactno;
     private String unitLocation;
     private String refname;
     private String unitname;
     private Set guardUniformReturns = new HashSet(0);
     private Set guardUniformIssues = new HashSet(0);

    public Securityguard() {
    }

	
  
    public Securityguard(Long empcode, String firstname, String midname, String lastname, Long contactno, String unitLocation, String refname, String unitname) {
        this.empcode = empcode;
        this.firstname = firstname;
        this.midname = midname;
        this.lastname = lastname;
        this.contactno = contactno;
        this.unitLocation = unitLocation;
        this.refname = refname;
        this.unitname = unitname;
    }
   
    
    
    
    
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getMidname() {
        return this.midname;
    }
    
    public void setMidname(String midname) {
        this.midname = midname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Long getContactno() {
        return this.contactno;
    }
    
    public void setContactno(Long contactno) {
        this.contactno = contactno;
    }
    public String getUnitLocation() {
        return this.unitLocation;
    }

    public Long getEmpcode() {
        return empcode;
    }

    public void setEmpcode(Long empcode) {
        this.empcode = empcode;
    }

    public String getUnitname() {
        return unitname;
    }

    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }
    
    
    
    public void setUnitLocation(String unitLocation) {
        this.unitLocation = unitLocation;
    }
    public String getRefname() {
        return this.refname;
    }
    
    public void setRefname(String refname) {
        this.refname = refname;
    }
    public Set getGuardUniformReturns() {
        return this.guardUniformReturns;
    }
    
    public void setGuardUniformReturns(Set guardUniformReturns) {
        this.guardUniformReturns = guardUniformReturns;
    }
    public Set getGuardUniformIssues() {
        return this.guardUniformIssues;
    }
    
    public void setGuardUniformIssues(Set guardUniformIssues) {
        this.guardUniformIssues = guardUniformIssues;
    }




}


